---
title: "Precourse preparations"
---


## Required competences

### Knowledge
You should meet the learning outcomes of: 

- [Introduction to bulk RNA-Seq: From Quality Control to Pathway Analysis](https://www.sib.swiss/training/course/20250922_IRNAS)
- [Introduction to Sequencing Data Analysis](https://www.sib.swiss/training/course/20251119_ISEDA), [First Steps with R in Life Sciences](https://www.sib.swiss/training/course/20251013_FSWR)
- [Single-Cell Transcriptomics with R](https://www.sib.swiss/training/course/20241112_ISCTR)

In summary, participants must already have a basic knowledge in:
- Next Generation Sequencing (NGS) techniques
- Analyzing gene expression data
- Dimensionality reduction (PCA, UMAP)
- Graph-based clustering 
- `R` (evaluate your `R` skills [here](https://docs.google.com/forms/d/e/1FAIpQLSdIyeuabd_ZOWXgI1MWHapmaOMu20L9ESkLDZiWnpmkpujyOg/viewform?usp=sf_link))
- `UNIX` (self-assess your skills with the e-learning course [`UNIX` Fundamentals](https://www.sib.swiss/training/course/2012_UNIXF), and this [quiz](https://docs.google.com/forms/d/e/1FAIpQLSd2BEWeOKLbIRGBT_aDEGPce1FOaVYBbhBiaqcaHoBKNB27MQ/viewform?usp=sf_link))

### Technical

Attendees should have a Wi-Fi enabled computer. An **online `R` and `RStudio` environment** will be provided. In order to access that environment your computer needs to be able to access http websites (not https). You can check this by browsing to [http://www.httpforever.com](http://www.httpforever.com). However, in case you wish to perform the practical exercises on your own computer, please take a moment to install the following before the course:

- [R](https://cran.r-project.org/) version > 4.5. 
- Latest RStudio version, the [free version](https://rstudio.com/products/rstudio/download/) is perfectly fine.
- The R packages necessary for the course. Find the [`renv`](https://rstudio.github.io/renv/) to install them [here](https://github.com/sib-swiss/spatial-transcriptomics-training/blob/master/renv.lock). 
